### ISSUE TITLE
Request for a Initiating Event Feature

### ISSUE THREAD

**Issue by ronpearl** [umanghome/swipe-listener#13]
Your application works great, however we are trying to use it for a mobile menu and have a suggestion for you that could be a possible added feature. Currently our mobile menu is just that, will only be used on mobile. Since we are attaching this swipe event to most of the page (so we can open the mobile menu on swipe) it also catches swipe events made by a mouse cursor. 

What we were thinking is that maybe you could add a variable to your custom event that checks to see if the user used a mouse to initiate the swipe, or if they used a touch. This would allow us to not assume a users environment based upon screen size and only make this swipe event available if they are physically swiping in a direction instead of using the mouse. Then we could read this variable from the event and decide if we want to continue processing the results of the swipe action.

In the meantime we may just fork and edit as needed, but this could be a great feature to add since you are already using a good custom event to track the other necessary data.

**Comment by umanghome** [comment]
@ronpearl Did you make a fork? If yes, could you make a PR to get this added. If not, I can work on adding this.

**Comment by ronpearl** [comment]
Unfortunately not, instead we ended up catching the event previous to instantiating the swipe listener.

**Comment by umanghome** [comment]
@ronpearl - Support for this was added in `1.0.7`, take a look at the [changelog](https://github.com/umanghome/swipe-listener/blob/master/CHANGELOG.md#107).

**Comment by ronpearl** [comment]
Awesome! I appreciate your responsiveness on this request. We are currently using our way around this and will be testing your implementation in the near future.
