### ISSUE TITLE
Consider exporting ES6-compatible object

### ISSUE THREAD

**Issue by Sebazzz** [umanghome/swipe-listener#15]
Consider exporting the module as a ES6 compatible module. ES6 module cannot have directly callable functions, but export something in the form of `{ default: … }`.

In this case you probably want backwards compatibility, and do something like this:

      module.exports = SwipeListener;
      module.exports.default = SwipeListener;

**Comment by SamuelGrave** [comment]
on it 👍

**Comment by umanghome** [comment]
Started exporting `default` as well in `v1.1.0`.
