### ISSUE TITLE
Make listening to mouse events optional

### ISSUE THREAD

**Issue by mimecuvalo** [umanghome/swipe-listener#16]
(Related to issue #5)

There are false positives that appear when using swipe-listener. Specifically, on desktop when selecting/highlighting text, it can register as a swipe event because of swipe-listener listens for mouse events. Would be great to make mouse listening an option that one can disable. In my case, I only need it specifically for mobile/touch-screen enabled devices.

Thanks for your consideration!

**Comment by umanghome** [comment]
Thanks for reporting. We can add configuration options to toggle both mouse and touch options.

**Comment by umanghome** [comment]
Added options in `v1.1.0`. Refer to the updated docs for the exact options.

**Comment by mimecuvalo** [comment]
Thank you!
