### ISSUE TITLE
IE Compatibility

### ISSUE THREAD

**Issue by banisirohi** [umanghome/swipe-listener#18]
Is this library IE compatible.
I'm getting an error-
'TouchEvent' is undefined at line 45338
![image](https://user-images.githubusercontent.com/30039512/60059422-99782600-9740-11e9-819c-699cf0bc8478.png)

**Comment by umanghome** [comment]
I didn't look at the compatibility with IE. I'll take a look and get back on this. Might require a version bump too.

**Comment by umanghome** [comment]
@banisirohi Can you tell me which version of IE you faced this on?

**Comment by umanghome** [comment]
Fixed in `v1.1.0`

**Comment by banisirohi** [comment]
@umanghome It was happening on IE 11. Thank you for fixing this.
